### ISSUE TITLE
Multiple IR units

### ISSUE THREAD

**Issue by Caboz** [homeassistantchina/custom_components#5]
Hello,

I have 4 xiaomi IR units all configured and working.

But there is a problem, I can't differentiate between the switches, they are all named chuang_mi_ir_switch.

I tried to customise the name but with no luck, the entity is switch.chuang_mi_ir_switch for all the switches and if I restart they are randomly numbered 1, 2,3...

My configuration is as follows:

```

switch:
  - platform: chuangmi_ir
    host: !secret kitchenchuangmi_ip
    name: "kitchenremote"
    token: !secret kitchenchuangmi_key
    switches:
      daikincool1:
        command_on: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAjYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAAAAAABAQEBAAAAAAAAAAAAAQEAAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQEAAA'
        command_off: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAkYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAABAAABAQEBAAAAAAAAAAAAAAABAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAAA'

  - platform: chuangmi_ir
    host: !secret livingroomchuangmi_ip
    name: "livingroomremote"
    token: !secret livingroomchuangmi_key
    switches:
      daikincool2:
        command_on: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAjYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAAAAAABAQEBAAAAAAAAAAAAAQEAAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQEAAA'
        command_off: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAkYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAABAAABAQEBAAAAAAAAAAAAAAABAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAAA'

  - platform: chuangmi_ir
    host: !secret stydychuangmi_ip
    name: "studyremote"
    token: !secret studychuangmi_key
    switches:
      daikincool3:
        command_on: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAjYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAAAAAABAQEBAAAAAAAAAAAAAQEAAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQEAAA'
        command_off: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAkYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAABAAABAQEBAAAAAAAAAAAAAAABAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAAA'

  - platform: chuangmi_ir
    host: !secret bedroomchuangmi_ip
    name: "bedroomremote"
    token: !secret bedroomchuangmi_key
    switches:
      daikincool4:
        command_on: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAjYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAAAAAABAQEBAAAAAAAAAAAAAQEAAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQEAAA'
        command_off: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAkYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAABAAABAQEBAAAAAAAAAAAAAAABAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAAA'

```

**Comment by Caboz** [comment]
I changed my configuration as follows and all is working better:
```
# Xiaomi Mi IR
switch:
  - platform: chuangmi_ir
    host: !secret kitchenchuangmi_ip
    token: !secret kitchenchuangmi_key
    switches:
      daikincool1:
        name: "kitchenremote"
        command_on: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAjYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAAAAAABAQEBAAAAAAAAAAAAAQEAAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQEAAA'
        command_off: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAkYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAABAAABAQEBAAAAAAAAAAAAAAABAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAAA'

  - platform: chuangmi_ir
    host: !secret livingroomchuangmi_ip
    token: !secret livingroomchuangmi_key
    switches:
      daikincool2:
        name: "livingroomremote"
        command_on: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAjYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAAAAAABAQEBAAAAAAAAAAAAAQEAAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQEAAA'
        command_off: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAkYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAABAAABAQEBAAAAAAAAAAAAAAABAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAAA'

  - platform: chuangmi_ir
    host: !secret stydychuangmi_ip
    token: !secret studychuangmi_key
    switches:
      daikincool3:
        name: "studyremote"
        command_on: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAjYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAAAAAABAQEBAAAAAAAAAAAAAQEAAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQEAAA'
        command_off: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAkYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAABAAABAQEBAAAAAAAAAAAAAAABAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAAA'

  - platform: chuangmi_ir
    host: !secret bedroomchuangmi_ip
    token: !secret bedroomchuangmi_key
    switches:
      daikincool4:
        name: "bedroomremote"
        command_on: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAjYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAAAAAABAQEBAAAAAAAAAAAAAQEAAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAABAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAEAAAAAAQEAAA'
        command_off: 'Z6VHAq8BAAALBQAAuQYAAH0NAAAkYwAA8IcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAQABAAAAAQEAAAAAAAAAAAAAAAAAAAAAAQEBAAEAAQEFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAEAAAAAAQABAAABAAABAQEBAAAAAAAAAAAAAAABAAAFAjEAAAABAAAAAAEAAQEAAQEBAQEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQEAAAABAAABAQAAAAAAAAAAAAABAQEBAAEAAQEBAQEAAAAAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEAAA'

```
